openapi_redoc.jsonapi:
  path: '/openapi-redoc/jsonapi'
  defaults:
    _controller: '\Drupal\openapi_redoc\Controller\DocController::generateDocs'
    _title: 'JSON API Documentation'
  requirements:
    _permission: 'access openapi api docs'
